# Enable colors
set -g default-terminal "xterm-256color"

# Remaps
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

unbind \"
unbind %
bind | split-window -h
bind - split-window -v

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Mouse mode
set -g mouse on
